# -*- coding: utf-8 -*-
"""WaterPotability.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1v0kzXEXwtbdIViB2AgtXEn0oFZKaz5XS
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

data=pd.read_csv("/content/water_potability.csv")
data.head(10)

data.dtypes

data.shape

data.info()

data.describe()

data.isnull().sum()

data.fillna(data.mean(),inplace=True)

data.isnull().sum()

data.Potability.value_counts()

plt.pie(data["Potability"].value_counts(),labels=["Non-Potability","Potability"],autopct="%0.2f")
plt.show()

x=data.drop("Potability",axis=1)
y=data["Potability"]

x

y

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=10)

x_train

y_train

from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
tree=DecisionTreeClassifier()

tree.fit(x_train,y_train)

predict=tree.predict(x_test)

score=accuracy_score(y_test,predict)

print("Accuracy Score:",score)